spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: yourpassword
        driverClassName: com.mysql.jdbc.Driver
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: create